---
- name: Check if wordpress is installed
  stat: path={{ wordpress.dir }}
  register: wordpressInd

- name: Download latest wordpress
  get_url: url={{ wordpress.downloadUrl }} dest={{ wordpress.downloadPath }}
  when: (wordpressInd.stat.exists == False) or ({{ forceInstall|default(False)|bool }})

- name: Unpack wordpress
  unarchive: src={{ wordpress.downloadPath }} dest={{ wordpress.installationDir }} owner=vagrant group=vagrant
  when: (wordpressInd.stat.exists == False) or ({{ forceInstall|default(False)|bool }})

- name: Copy wordpress config
  template: src=wp_config.php.j2 dest="{{ wordpress.dir }}/wp-config.php" force=yes
  when: (wordpressInd.stat.exists == False) or ({{ forceInstall|default(False)|bool }})
