---
- name: Install all dependencies
  apt: name={{ item }} state=present
  with_items:
    - git
    - mcrypt
    - php5
    - php5-mysql
    - php5-cli
    - php5-curl
    - php5-fpm
    - php5-intl
    - php5-json
    - php5-mcrypt
    - php5-mongo
    - apache2
    - libapache2-mod-php5
    - python-mysqldb

- name: Set PHP date.timezone
  ini_file:
    dest: /etc/php5/{{ item }}/php.ini
    section: "Date"
    option: "date.timezone"
    value: "Europe/Bucharest"
    state: present
  with_items:
    - apache2
    - cli

- name: Ensure apache is running and enable it at boot
  service: 
    name: apache2 
    state: started 
    enabled: yes

- name: Enable apache mod rewrite
  apache2_module: 
    name: rewrite 
    state: present
  notify:
    - restart apache
