---
- name: Install mariadb server
  apt: 
    name: mariadb-server 
    state: latest

- name: Create mariadb user
  mysql_user:
    name: "{{ mariadb.user }}"
    password: "{{ mariadb.password }}"
    priv: "*.*:ALL"
    state: present
